workflows:
  build_release_apk:
    name: Build Release APK
    max_build_duration: 60
    environment:
      node: 18
      java: 17
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
    artifacts:
      - dist/**
